server:
  port: 9001
spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: pay-routh1
          uri: lb://provider-payment
          predicates:
            - Path=/pay/get/**
            #- After,- Before,- Between 在某个时间节点之前,之后或两个时间节点之间开放路由
        - id: pay-routh2
          uri: lb://provider-payment
          predicates:
            - Path=/pay/getgate/info/**